# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
file = pd.read_csv('random_cities.csv')

In [4]:
df = file

In [5]:
df

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Ilulissat,93,GL,1584329447,47,69.22,-51.10,-9.40,3.60
1,1,Ushuaia,40,AR,1584329445,71,-54.80,-68.30,53.60,1.96
2,2,Rikitea,3,PF,1584329417,79,-23.12,-134.97,79.63,5.68
3,3,Jasper,90,US,1584329424,81,37.20,-94.35,42.80,1.50
4,4,Saldanha,99,ZA,1584329475,63,-33.01,17.94,64.40,3.10
...,...,...,...,...,...,...,...,...,...,...
565,565,Haines Junction,7,CA,1584329602,92,60.75,-137.51,17.78,0.34
566,566,Little Rock,90,US,1584329603,81,34.75,-92.29,45.00,6.20
567,567,Marzuq,100,YE,1584329603,66,14.40,46.47,66.20,1.00
568,568,Gorom-Gorom,93,BF,1584329603,13,14.44,-0.24,78.33,4.78
569,569,Spencer,90,US,1584329418,81,43.14,-95.14,33.01,2.60

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:
# Configure google maps
gmaps.configure(api_key=g_key)

figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'}
    

fig = gmaps.figure(layout=figure_layout)

In [7]:
df_coordinates = df[['Lat', 'Lng']]
df_coordinates

       Lat     Lng
0    69.22  -51.10
1   -54.80  -68.30
2   -23.12 -134.97
3    37.20  -94.35
4   -33.01   17.94
..     ...     ...
565  60.75 -137.51
566  34.75  -92.29
567  14.40   46.47
568  14.44   -0.24
569  43.14  -95.14

[570 rows x 2 columns]

In [8]:
# Assign the marker layer to a variable
markers = gmaps.heatmap_layer(df_coordinates, weights=df["Humidity"])
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wiâ€¦

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [9]:
df_ideal = df.loc[df['Max Temp'] >= 65]
df_ideal = df_ideal.loc[df['Max Temp'] <= 80]

df_ideal

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
2,2,Rikitea,3,PF,1584329417,79,-23.12,-134.97,79.63,5.68
7,7,Ahipara,100,NZ,1584329476,74,-35.17,173.17,66.85,5.48
10,10,Cayenne,75,GF,1584329403,88,4.93,-52.33,77.00,2.96
11,11,Arraial do Cabo,0,BR,1584329477,83,-22.97,-42.03,77.90,11.88
17,17,MaÃ¯nÃ© Soroa,9,NE,1584329478,14,13.21,12.02,65.43,3.21
...,...,...,...,...,...,...,...,...,...,...
557,557,Jiwani,32,PK,1584329601,65,25.05,61.74,71.91,1.93
561,561,Poso,85,ID,1584329601,75,-1.40,120.75,75.78,2.13
563,563,Manono,100,CD,1584329602,95,-7.30,27.42,69.89,0.48
567,567,Marzuq,100,YE,1584329603,66,14.40,46.47,66.20,1.00
568,568,Gorom-Gorom,93,BF,1584329603,13,14.44,-0.24,78.33,4.78

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
df_hotel = df_ideal
df_ideal

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
2,2,Rikitea,3,PF,1584329417,79,-23.12,-134.97,79.63,5.68
7,7,Ahipara,100,NZ,1584329476,74,-35.17,173.17,66.85,5.48
10,10,Cayenne,75,GF,1584329403,88,4.93,-52.33,77.00,2.96
11,11,Arraial do Cabo,0,BR,1584329477,83,-22.97,-42.03,77.90,11.88
17,17,MaÃ¯nÃ© Soroa,9,NE,1584329478,14,13.21,12.02,65.43,3.21
...,...,...,...,...,...,...,...,...,...,...
557,557,Jiwani,32,PK,1584329601,65,25.05,61.74,71.91,1.93
561,561,Poso,85,ID,1584329601,75,-1.40,120.75,75.78,2.13
563,563,Manono,100,CD,1584329602,95,-7.30,27.42,69.89,0.48
567,567,Marzuq,100,YE,1584329603,66,14.40,46.47,66.20,1.00
568,568,Gorom-Gorom,93,BF,1584329603,13,14.44,-0.24,78.33,4.78

In [11]:
df_hotel['Hotel Name'] = ''
df_hotel

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
2,2,Rikitea,3,PF,1584329417,79,-23.12,-134.97,79.63,5.68,
7,7,Ahipara,100,NZ,1584329476,74,-35.17,173.17,66.85,5.48,
10,10,Cayenne,75,GF,1584329403,88,4.93,-52.33,77.00,2.96,
11,11,Arraial do Cabo,0,BR,1584329477,83,-22.97,-42.03,77.90,11.88,
17,17,MaÃ¯nÃ© Soroa,9,NE,1584329478,14,13.21,12.02,65.43,3.21,
...,...,...,...,...,...,...,...,...,...,...,...
557,557,Jiwani,32,PK,1584329601,65,25.05,61.74,71.91,1.93,
561,561,Poso,85,ID,1584329601,75,-1.40,120.75,75.78,2.13,
563,563,Manono,100,CD,1584329602,95,-7.30,27.42,69.89,0.48,
567,567,Marzuq,100,YE,1584329603,66,14.40,46.47,66.20,1.00,
568,568,Gorom-Gorom,93,BF,1584329603,13,14.44,-0.24,78.33,4.78,

In [12]:
df_hotel = df_hotel[['City', 'Country', 'Lng', 'Lat', 'Hotel Name']]
df_hotel = df_hotel.reset_index(drop=True)

In [13]:
df_hotel

                City Country     Lng    Lat Hotel Name
0            Rikitea      PF -134.97 -23.12
1            Ahipara      NZ  173.17 -35.17
2            Cayenne      GF  -52.33   4.93
3    Arraial do Cabo      BR  -42.03 -22.97
4        MaÃ¯nÃ© Soroa      NE   12.02  13.21
..               ...     ...     ...    ...        ...
155           Jiwani      PK   61.74  25.05
156             Poso      ID  120.75  -1.40
157           Manono      CD   27.42  -7.30
158           Marzuq      YE   46.47  14.40
159      Gorom-Gorom      BF   -0.24  14.44

[160 rows x 5 columns]

In [ ]:
# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# geocoordinates
target_coordinates = ''
target_radius = 5000
target_search = 'lodging'

# set up a parameters dictionary
payload = {
    "location": target_coordinates,
    "keyword": 'lodging',
    "radius": target_radius,
    "key": g_key
}

for idx, row in df_hotel.iterrows():
    
    hotel = {}
    
    payload['location'] = (f"{row['Lat']},{row['Lng']}")
    print(target_coordinates)         
    
    print(f"Trying to run #{idx} {row['City']}.")
    print(f"Attempting longitude and latitude {target_coordinates}.")
    
    # run a request using our params dictionary
    r = requests.get(base_url, params=payload)
    
    r_json = r.json()
    
    print(r.url)
    
    try:
        df_hotel.loc[idx, 'Hotel Name'] = r_json['results'][0]['name']
          
    except (IndexError):
          print('Zero Results, Skipping...')
    
    print('------------')

          
# This is where I left off. BRKN. Something is wrong with API but iteration is running.

Trying to run #0 Rikitea.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-23.12%2C-134.97&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #1 Ahipara.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-35.17%2C173.17&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #2 Cayenne.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=4.93%2C-52.33&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #3 Arraial do Cabo.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-22.97%2C-42.03&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #4 MaÃ¯nÃ© Soroa.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=13.21%2C12.02&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
Zero Results, Skipping...
------------

Trying to run #5 Kapaa.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=22.08%2C-159.32&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #6 Paoua.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=7.24%2C16.44&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #7 Bukama.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-9.2%2C25.85&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
Zero Results, Skipping...
------------

Trying to run #8 Ixtapa.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=20.7%2C-105.2&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #9 TaperoÃ¡.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-7.21%2C-36.83&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #10 Hobart.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-42.88%2C147.33&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #11 Puerto Ayora.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-0.74%2C-90.35&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #12 Buchanan.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=5.88%2C-10.05&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #13 Castro.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-24.79%2C-50.01&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #14 Busselton.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.65%2C115.33&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #15 New Norfolk.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-42.78%2C147.06&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #16 Natal.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-5.79%2C-35.21&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #17 Byron Bay.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-28.65%2C153.62&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #18 Tarrafal.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=15.28%2C-23.77&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #19 Kongolo.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-5.38%2C27.0&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #20 Hilo.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=19.73%2C-155.09&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #21 Bosaso.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=11.28%2C49.18&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #22 Hong Kong.
Attempting longitude and latitude .
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=22.29%2C114.16&keyword=lodging&radius=5000&key=AIzaSyAYPTNqqCdHIy97LYoRQ8zbwBpXyD_APLw
------------

Trying to run #23 Port Macquarie.
Attempting longitude and latitude .

In [ ]:
df_hotel

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in df_hotel.iterrows()]
locations = df_hotel[["Lat", "Lng"]].astype(float)

In [ ]:
# Add marker layer ontop of heat map
print_fig = fig.add_layer(gmaps.marker_layer(locations, info_box_content=hotel_info))
print_fig

# Display Map